version: '3.9'

services:
  db:
    image: postgres:16
    container_name: ${DB_CONTAINER_NAME}
    restart: always

    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}

    ports:
      - '5433:5432'

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DATABASE_USER}']
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: ${API_CONTAINER_NAME}
    restart: always

    depends_on:
      db:
        condition: service_healthy

    environment:
      APP_NAME: ${APP_NAME}
      APP_ENV: ${APP_ENV}

      DATABASE_DRIVER: ${DATABASE_DRIVER}
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}

      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_EXPIRES_MINUTES: ${JWT_EXPIRES_MINUTES}

      MASTER_OTP: ${MASTER_OTP}
      WATCHFILES_FORCE_POLLING: "true"

    ports:
      - '8000:8000'
      - '5678:5678'

    volumes:
      - .:/app

    command: >
      python -Xfrozen_modules=off
      -m debugpy --listen 0.0.0.0:5678
      -m uvicorn app.main:app
      --host 0.0.0.0
      --port 8000
      --reload
      --reload-dir app

volumes:
  postgres_data:
