version: '3.9'

services:
  db:
    image: postgres:16
    container_name: ${DB_CONTAINER_NAME}
    restart: always

    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}

    ports:
      - '${PORT}:5432' # host:container

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DATABASE_USER}']
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: ${API_CONTAINER_NAME}
    restart: always

    depends_on:
      db:
        condition: service_healthy

    volumes:
      - .:/app # dev only (remove in prod)

    environment:
      APP_NAME: ${APP_NAME}
      APP_ENV: ${APP_ENV}

      DATABASE_DRIVER: ${DATABASE_DRIVER}
      DATABASE_HOST: db
      DATABASE_PORT: 5432 # ✅ always container port
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_ECHO: ${DATABASE_ECHO}

      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_EXPIRES_MINUTES: ${JWT_EXPIRES_MINUTES}

      MASTER_OTP: ${MASTER_OTP}
      FIRST_ADMIN_EMAIL: ${FIRST_ADMIN_EMAIL}
      FIRST_ADMIN_MOBILE: ${FIRST_ADMIN_MOBILE}
      FIRST_ADMIN_NAME: ${FIRST_ADMIN_NAME}
      FIRST_ADMIN_AGE: ${FIRST_ADMIN_AGE}

    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'

    command: >
      sh -c "uvicorn app.main:app --host 0.0.0.0 --port ${SERVER_PORT} --reload"

volumes:
  postgres_data:
